vich_uploader:
    db_driver: orm

    mappings:
        region_images:
            uri_prefix:         '%region_images%'
            upload_destination: '%kernel.project_dir%/public%region_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        offre_images:
            uri_prefix:         '%offre_images%'
            upload_destination: '%kernel.project_dir%/public%offre_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer